Add lip-16 "Two-phase voting" draft
lidofinance/lido-improvement-proposals pull request #35
Opened 2022-06-06 15:45 UTC by folkyatina

Context
- Forum post: https://research.lido.fi/t/proposal-last-minute-vote-mitigation/2162
- ADR: https://hackmd.io/BlfaMs30TVeK8OyU6OI-1A
- Changes: https://github.com/lidofinance/aragon-apps/pull/8

2022-06-06 18:45 UTC, TheDZhon requested changes
It's well-formed, exhaustive, and easy to read :+1: 
I propose to implement some corrections to approach perfection :100:

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +and the other — for voting
\+ only 'against' (i.e. to raise voter's objection)

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +the overall vote time to be 72h :
May add the reference to the 72h LIP: https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-4.md

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +Proposed timeframes can be changed later using the added methods.
I suggest writing: 'using newly added methods of the `Voting` contract'.

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +3rd-party integrations can prepare its code for the changes, and StETH-holders
it's better to use `stETH` capitalization pattern

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +cancel the vote then to make it pass and making our governance more
'our governance' would be sound much better as 'Lido DAO governance' :+1:

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +We propose to add the following field to `Voting.sol` contract to store
to **the** `Voting` contract

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +`voteTime > objectionPhaseTime` invariant. The similar `require` is added to
'added to **the*** ...'

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +__NB!__ Method should be used with caution as it changes all the votes
**The** method ...

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +New `require` in `vote()` checks that  only 'no' votes are accepted during the
extra space

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +`newVote()` and `vote()` methods and removing all related logic. An event
**The** event ...

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +also, current `phase` is added to `getVote` return value
'is added as additional `getVote` return value' or 'is appended to the `getVote` return values list'

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +And to maintain consistency `authP` modifier in both methods is replaced by
missing comma before the `authP` word.

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +The mitigation does not fully mitigate the 'last moment vote' problem for
does not fully resolve

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +
May add the explicit note about compatibility with the 72h-long voting (preserving the same timeframe to deliver the necessary changes, don't want to extend it further to be able to react reasonably quickly).

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +We propose to split each vote timeframe into two phases, while maintaining
may remove the comma here

2022-06-06 18:45 UTC, TheDZhon commented on LIPS/lip-16.md
> +allowed the premature execution of a vote if more than a half of a total
'more than half of the total issued ...' (articles usage should be improved)

2022-06-07 05:12 UTC, arwer13 requested changes

2022-06-07 05:12 UTC, arwer13 commented on LIPS/lip-16.md
> +cancel the vote then to make it pass and making our governance more
here is a type: then -> than

2022-06-07 05:12 UTC, arwer13 commented on LIPS/lip-16.md
> +Duration of the Main phase is calculated as `voteTime - objectionPhaseTime`.
Duration --> The duration

2022-06-07 05:12 UTC, arwer13 commented on LIPS/lip-16.md
> +cancelling the vote and even introduce a more comfortable objection period for
cancelling -> canceling

2022-06-07 05:12 UTC, arwer13 commented on LIPS/lip-16.md
> +cancelling the vote and even introduce a more comfortable objection period for
introduce -> introduces

2022-06-07 05:12 UTC, arwer13 commented on LIPS/lip-16.md
> +supported a previous version should remain functional. They will revert with
a previous -> the previous

2022-06-07 05:12 UTC, arwer13 commented on LIPS/lip-16.md
> +supported a previous version should remain functional. They will revert with
Who 'they' in 'They will revert ..."?

2022-06-07 05:12 UTC, arwer13 commented on LIPS/lip-16.md
> +# Protocol safeguards. Two-phase voting.
the last period is excess in the header?

2022-06-07 08:04 UTC, folkyatina commented on LIPS/lip-16.md
> +cancelling the vote and even introduce a more comfortable objection period for
both are possible, actually

2022-06-07 10:32 UTC, TheDZhon approved these changes
Fuel is pumping engines 🏎️

2022-06-07 11:30 UTC, arwer13 approved these changes

2022-06-07 12:03 UTC, merged