Add clarification about getOracleReportLimits() backward compatibility
lidofinance/lido-improvement-proposals pull request #61
Opened 2024-07-11 11:41 UTC by vp4242

Add clarification about getOracleReportLimits() backward compatibility

2024-07-17 14:34 UTC, folkyatina approved these changes
Looks sane

2024-07-17 20:21 UTC, TheDZhon requested changes
:+1: a little fix is suggested

2024-07-17 20:21 UTC, TheDZhon commented on LIPS/lip-23.md
> +However, new sanity checker implies changes in the report limits. Oracle consumes the limits via the `getOracleReportLimits()` function. For that reason `oneOffCLBalanceDecreaseBPLimit` should be mar
```suggestion
However, new sanity checker implies changes in the report limits. The off-chain [oracle daemon](https://github.com/lidofinance/lido-oracle) consumes the limits via the `getOracleReportLimits()` function. For that reason, `oneOffCLBalanceDecreaseBPLimit` should be marked as deprecated, and all new parameters should be added at the end of the list.
```

2024-07-18 14:20 UTC, TheDZhon approved these changes
:+1:

2024-07-18 14:20 UTC, merged